-- Creation de la BDD
CREATE DATABASE quizz_cda CHARSET utf8mb4;
USE quizz_cda;

-- Création des tables
CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
firstname VARCHAR(50),
lastname VARCHAR(50),
pseudo VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
`password` VARCHAR(100) NOT NULL,
`status` BOOL DEFAULT true,
`active` BOOL DEFAULT true,
`deleted` BOOL DEFAULT true,
roles VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME,
deleted_at DATETIME,
media_id INT
)ENGINE=InnoDB;

CREATE TABLE media(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
url VARCHAR(255) NOT NULL,
alt VARCHAR(255) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE category(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`name` VARCHAR(50) UNIQUE NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE quizz(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
title VARCHAR(50) NOT NULL,
`description` VARCHAR(255) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
author_id INT NOT NULL,
media_id INt NOT NULL
)ENGINE=InnoDB;

CREATE TABLE score(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
quizz_id INT NOT NULL,
users_id INT NOT NULL
)ENGINE=InnoDB;

ALTER TABLE users
ADD CONSTRAINT fk_add_media
FOREIGN KEY(media_id)
REFERENCES media(id);